feat: add commitlint and husky
softorwhite/react-blog pull request #10
Opened 2023-01-27 00:51 UTC by softorwhite

close #1

2023-01-27 02:04 UTC, piro0919 requested changes

2023-01-27 02:04 UTC, piro0919 commented on package.json
> +  "devDependencies": {
[imo]

Next.js の v13 から devDependencies を使わない方向に変わったので、dependencies にまとめちゃっても良いかもです。 👀

2023-01-27 02:04 UTC, piro0919 commented on package.json
> +    "husky": "^8.0.3"
[must]

バージョンは固定したほうが良いですね！
インストールを行う際 `--exact` を付与してみてください。 👍 

rel https://stackoverflow.com/questions/41003470/npm-install-the-exact-package-version-specified-in-package-json

2023-01-29 12:38 UTC, softorwhite commented on package.json
> +    "husky": "^8.0.3"
そうですね。ありがとうございます！修正しました！[abff8d9](https://github.com/softorwhite/react-blog/pull/10/commits/abff8d95ff995a483e5ef0bbf13b2864bade166c)

2023-01-29 12:39 UTC, softorwhite commented on package.json
> +  "devDependencies": {
dependenciesに全部まとめました！ありがとうございます。
[abff8d9](https://github.com/softorwhite/react-blog/pull/10/commits/abff8d95ff995a483e5ef0bbf13b2864bade166c)

2023-01-29 13:07 UTC, piro0919 commented
@softorwhite 

修正を行った後再度レビューを依頼する場合は、Reviwers にある更新アイコンっぽいボタンを押下するようお願いしますー。 🙇 
<img width="337" alt="image" src="https://user-images.githubusercontent.com/30312044/215328109-b755ffd6-0a59-434e-a9fd-2ada336406e8.png">

2023-01-29 14:02 UTC, piro0919 approved these changes
LGTM 👍

2023-01-29 14:12 UTC, merged